# @format

openapi: 3.0.0
info:
  title: ASC Sample
  description: Sample API for ASC 2022
    Demonstrate the effect of JSON Schema structure on code generation.
  version: 0.0.1
  contact:
    email: David.Biesack@gmail.com

servers:
  - url: /sample

tags:
  - name: Geometry
    description: Geometry
paths:
  /point:
    get:
      summary: Get a point
      description: Get a point
      operationId: getPoint
      tags:
        - Geometry
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/point'

components:

  schemas:

    point:
      title: A Point
      description: A Point in 2-D space
      type: object
      allOf:
        - $ref: '#/components/schemas/cartesianPoint2D'
        - $ref: '#/components/schemas/polarPoint2D'
    cartesianPoint2D:
      title: A cartesian point
      description: A cartesian point in 2-D space
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: number
          format: double
        y:
          type: number
          format: double
    polarPoint2D:
      title: A point in Polar 2-D space
      description: A point in 2-D space, polar coordinates
      type: object
      required:
        - rho
        - theta
      properties:
        rho:
          type: number
          format: double
        theta:
          type: number
          format: double

    # Tip: use a `type` property to identify the run-time type
    # with an enum
    point2DWithInlineType:
      title: A Point
      description: A Point in 2-D space
      type: object
      properties:
        type:
          type: string
          enum: [ cartesian, polar ]
        cartesian:
          $ref: '#/components/schemas/cartesianPoint2D'
        polar:
          $ref: '#/components/schemas/polarPoint2D'

    # Tip: Avoid inline (unnamed, anonymous) object or enum schemas as used in point2DWithInlineType
    point2D:
      title: A Point
      description: A Point in 2-D space
      type: object
      required: [ type ]
      properties:
        type:
          $ref: '#/components/schemas/pointType'
        cartesian:
          $ref: '#/components/schemas/cartesianPoint2D'
        polar:
          $ref: '#/components/schemas/polarPoint2D'
    pointType:
      title: Point Type
      description: The type of a geometric point in 2D space.
      type: string
      enum: [ cartesian, polar ]

    point3D:
      title: 3D Point
      description: A point in 3-D space, either cartesian or polar coordinates.
      type: object
      required: [ type ]
      properties:
        type:
          $ref: '#/components/schemas/pointType'
      oneOf:
        - $ref: '#/components/schemas/cartesianPoint3D'
        - $ref: '#/components/schemas/polarPoint3D'
      discriminator:
          propertyName: type
          mapping:
            cartesian: '#/components/schemas/cartesianPoint3D'
            polar: '#/components/schemas/polarPoint3D'

    cartesianPoint3D:
      title: Cartesian coordinate point in 3-D space
      description: Cartesian coordinate point in 3-D space.
        Used when a `point3D` object has `type` of `cartesian`.
      type: object
      allOf:
        - $ref: '#/components/schemas/point3D'
        - $ref: '#/components/schemas/cartesianPoint2D'
        - type: object
          required: [ z ]
          properties:
            z:
              type: number
              format: double

    polarPoint3D:
      title: Polar coordinate point in 3-D space
      description: Polar coordinate point in 3-D space.
        Used when a `point3D` object has `type` of `polar`.
      type: object
      allOf:
        - $ref: '#/components/schemas/point3D'
        - $ref: '#/components/schemas/polarPoint2D'
        - type: object
          required: [ phi ]
          properties:
            phi:
              type: number
              format: double
